### ISSUE TITLE
"github" should possibly be named something else, like "repository"

### ISSUE THREAD

**Issue by ell1e** [codelani/codelani#15]
I suggest the data entry "github" should possibly be named something else, like "repository". There are other places like [gitlab.com](https://gitlab.com), so naming a data key after just one platform (no matter how popular) when quite a few others are used just is a bit weird.

**Comment by codelani** [comment]
Gitlab should be a property as well. Just pushed. Good suggestion! Thanks!

**Comment by codelani** [comment]
What seems to work best is to start specific but also have a catch all for things that use none of the major git hosts.

**Comment by ell1e** [comment]
Yeah I would just name it "repository" or similar. Almost no project has multiple, but there sure are way more ways to host code than gitlab or gthub. So I don't think having these keys makes a lot of sense.

**Comment by codelani** [comment]
> Almost no project has multiple

The key word is "almost". CodeLani is about helping people build the next great programming language. So a lot of attention is put into making things flexible to be able to track outliers. Perhaps we will see some interesting patterns in languages that mirror their repos to GitLab and GitHub and X. Or maybe we will see a fluctuations in popularity between the two. Doing it this way makes it ever so much easier to track that sort of thing. You could argue that we could just allow multiple "repoUrl" properties, and then parse all of those at report time. That's also a decent approach, but having a separate property makes ad hoc parsing a lot easier. A simple /^gitlab /g is enough to show many languages use gitlab.

**Comment by codelani** [comment]
Thank you for bringing this up. Always helpful when I'm forced to articulate some of these seemingly odd design decisions.

**Comment by ell1e** [comment]
Yeah I think you should just allow "repository" multiple times. It is trivial to detect github and gitlab from the URL, so the current format just seems messier for no benefit.

**Comment by codelani** [comment]
> for no benefit

I do ad hoc parsing things like this "A simple /^gitlab /g is enough to show many languages use gitlab" many times a day.

**Comment by ell1e** [comment]
So why don't you write a quick script to look at the URL instead? That really doesn't seem like a strong use case for me to make the format weird for everyone, IMHO.
