### ISSUE TITLE
Invalid Julia (package count) info

### ISSUE THREAD

**Issue by PallHaraldsson** [codelani/codelani#16]
Hi, I like your site that I just discovered.

Regarding Julia, its package manager, the repository moved, so your info at:

https://codelani.com/posts/does-every-programming-language-have-a-central-package-repository.html

i.e. not only 1,906 (not sure even at the time, don't recall when the moved happened).

i.e. you could substitute (if you need accurate numbers)
https://github.com/JuliaRegistries/General

or juliahub.com (for user-friendly access):

for https://julialang.org/packages/

everywhere.

**Comment by codelani** [comment]
Thanks @PallHaraldsson! I just got back to updating the site. I need to update that whole post in general, but for now I fixed Julia with your JuliaHub suggestion. Thank you!

**Comment by PallHaraldsson** [comment]
Thanks,

I see Smalltalk with 4,534 packages in the list, but in the graph seems much higher (above Julia).

Otherwise the graph might be in sync with the list (update the list? Or might some languages have more than one package manager and you add up numbers, e.g. some lower number for Smalltalk?).

**Comment by breck7** [comment]
Okay I updated the old chart, with the updated Julia count, and I added a link to an Observable notebook (I previously made it in R Studio).

Before: 

![packages-repos-before](https://user-images.githubusercontent.com/74692/175755483-b5940f0f-16b6-4fa9-966c-e578b0a2d0b5.png)

After:
![](https://codelani.com/images/packages-repos.png)

I have 2 more items on the todo list here:
[] Update the other package repositories with 2022 numbers
[] Update the observable notebook to pull the latest data automatically

**Comment by codelani** [comment]
Okay I updated the old chart, with the updated Julia count, and I added a link to an Observable notebook (I previously made it in R Studio).

Before: 
![packages-repos-old](https://user-images.githubusercontent.com/74692/175755549-d9936aa3-c3e9-401c-9cbe-4780408357a5.png)



After:
![](https://codelani.com/images/packages-repos.png)

I have 2 more items on the todo list here:
[] Update the other package repositories with 2022 numbers
[] Update the observable notebook to pull the latest data automatically
